name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b 3.3.1 "$GITHUB_WORKSPACE/_flutter"
          echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH

      - name: Add path
        run: echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      - name: Download Flutter packages
        run: flutter pub get

      - name: Create .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_LIFFID: ${{ secrets.LIFFID }}
          envkey_GAS_URL: ${{ secrets.GAS_URL }}

      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTER_LIFF_SCHEDULER }}'
          channelId: live
          projectId: flutter-liff-scheduler
